name: Main

on:
  workflow_run:
    workflows: ["Workflow_1", "Workflow_2", "Workflow_3"]  # Ensure these workflows are correctly named
    types:
      - completed

jobs:
  final_check:
    runs-on: ubuntu-latest
    if: ${{ success() }}  # Ensures that this job runs only if all workflows succeeded

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure all checks passed
        run: |
          required_checks=("Workflow_1" "Workflow_2" "Workflow_3")

          # Fetch check run statuses from the GitHub API
          for i in {1..10}; do
            echo "Fetching check run statuses..."
            gh api -X GET \
              repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/check-runs \
              | jq '.check_runs[] | select(.conclusion=="success")' > successful_checks.json

            missing_checks=()
            for check in "${required_checks[@]}"; do
              if ! grep -q "$check" successful_checks.json; then
                missing_checks+=("$check")
              fi
            done

            if [ ${#missing_checks[@]} -eq 0 ]; then
              echo "All required checks passed!"
              break
            fi

            echo "Missing checks: ${missing_checks[*]}. Retrying in 10 seconds..."
            sleep 10
          done

          if [ ${#missing_checks[@]} -ne 0 ]; then
            echo "Required checks did not pass: ${missing_checks[*]}"
            exit 1
          fi
