name: Main

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested]

jobs:
  final_check:
    name: Final Check
    runs-on: ubuntu-latest
    steps:
      - name: Wait for all checks
        run: |
          echo "Waiting for Lint, Unit Tests, and Format Check"
          gh api \
            -X GET \
            repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/check-runs \
            | jq '.check_runs[] | select(.conclusion=="success")' > successful_checks.json

      - name: Ensure all checks passed
        run: |
          required_checks=("Lint Check" "Unit Tests" "Format Check")
          for check in "${required_checks[@]}"; do
            if ! grep -q "$check" successful_checks.json; then
              echo "Required check $check did not pass or is missing"
              exit 1
            fi
          done
          echo "All checks passed!"
